// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"goTraining/Week04/internal/biz"
	"goTraining/Week04/internal/dao"
	"goTraining/Week04/internal/service"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

func InitHandler(db *sql.DB) service.Handler {
	repo := dao.NewRepo(db)
	stringService := biz.NewStringService(repo)
	handler := service.NewHandler(stringService)
	return handler
}
